### ISSUE TITLE
Adding an SSH key in Gogs throws error 500

### ISSUE THREAD

**Issue by nurtext** [microbox/gogs#2]
Error in logfile:

    2015/08/10 11:00:31 [1;31m[...ters/user/setting.go:342 SettingsSSHKeysPost()] [E] AddPublicKey: addKey: open /data/git/.ssh/authorized_keys: permission denied

**Comment by Luzifer** [comment]
Cause: https://github.com/microbox/gogs/blob/master/gogs.sh#L40

The directory is not accessible and for this reason the `authorized_keys` file in this directory cannot get written.
